############################
## CHANGE THESE
############################

baseURL: 'https://jeryRazakarison.github.io/nagordcom'
title: nagordcom

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


