############################
## CHANGE THESE
############################

baseURL: 'https://nagord.com'
title: Nagord
publishDir: doc

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


