############################
## Author
############################

author:
  name: Nagord
  image: nagordlogo2.png
  greeting: "Mobile apps development"

############################
## Links
############################

links:
  # - github: https://github.com/jeryRazakarison/nagordcom
  # - link: https://github.com/jeryRazakarison/nagordcom#readme
  # - website: 
  # - x-twitter: 
  # - mastodon: 
  - linkedin: https://www.linkedin.com/in/jeryraza/
  # - instagram: 
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  # - email: 
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  # - medium: 
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: Nagord
description: "Site build with Hugo"
images:
  - thumbnail.png
